# Generated by Django 4.2.11 on 2024-03-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_person_options_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
    ]
