# Generated by Django 4.2.11 on 2024-03-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_doctor_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=30),
        ),
    ]
