# Generated by Django 4.2.11 on 2024-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
