# Generated by Django 4.2.11 on 2024-03-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_person_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile_picture',
        ),
    ]
