# Generated by Django 4.2.11 on 2024-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_person_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profile_pictures/'),
            preserve_default=False,
        ),
    ]
