# Generated by Django 4.2.11 on 2024-03-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_person_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
