# Generated by Django 4.2.11 on 2024-04-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_remove_doctor_rating_alter_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
