# Generated by Django 4.2.11 on 2024-04-02 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_alter_person_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Mobile number must be between 10 and 15 digits long.', regex='^\\d{10,15}$')]),
        ),
    ]
