# Generated by Django 4.2.11 on 2024-03-10 04:21

import appointment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0009_alter_doctor_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TimeField()),
                ('date', models.DateField(validators=[appointment.models.validate_future_date])),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Pending', max_length=200)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
