# Generated by Django 4.2.11 on 2024-03-11 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 3, 12), '2024-03-12'), (datetime.date(2024, 3, 13), '2024-03-13'), (datetime.date(2024, 3, 14), '2024-03-14'), (datetime.date(2024, 3, 15), '2024-03-15'), (datetime.date(2024, 3, 16), '2024-03-16'), (datetime.date(2024, 3, 17), '2024-03-17'), (datetime.date(2024, 3, 18), '2024-03-18')], max_length=20),
        ),
    ]
