# Generated by Django 4.2.11 on 2024-03-12 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 3, 11), '11-03-2024'), (datetime.date(2024, 3, 10), '10-03-2024'), (datetime.date(2024, 3, 9), '09-03-2024'), (datetime.date(2024, 3, 8), '08-03-2024'), (datetime.date(2024, 3, 7), '07-03-2024'), (datetime.date(2024, 3, 6), '06-03-2024'), (datetime.date(2024, 3, 5), '05-03-2024'), (datetime.date(2024, 3, 13), '13-03-2024'), (datetime.date(2024, 3, 14), '14-03-2024'), (datetime.date(2024, 3, 15), '15-03-2024'), (datetime.date(2024, 3, 16), '16-03-2024'), (datetime.date(2024, 3, 17), '17-03-2024'), (datetime.date(2024, 3, 18), '18-03-2024'), (datetime.date(2024, 3, 19), '19-03-2024')], max_length=20),
        ),
    ]
