# Generated by Django 4.2.11 on 2024-03-29 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='issue',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 3, 30), '30-03-2024'), (datetime.date(2024, 3, 29), '29-03-2024'), (datetime.date(2024, 3, 28), '28-03-2024'), (datetime.date(2024, 3, 27), '27-03-2024'), (datetime.date(2024, 3, 26), '26-03-2024'), (datetime.date(2024, 3, 25), '25-03-2024'), (datetime.date(2024, 3, 24), '24-03-2024'), (datetime.date(2024, 3, 23), '23-03-2024'), (datetime.date(2024, 3, 31), '31-03-2024'), (datetime.date(2024, 4, 1), '01-04-2024'), (datetime.date(2024, 4, 2), '02-04-2024'), (datetime.date(2024, 4, 3), '03-04-2024'), (datetime.date(2024, 4, 4), '04-04-2024'), (datetime.date(2024, 4, 5), '05-04-2024'), (datetime.date(2024, 4, 6), '06-04-2024')], max_length=20),
        ),
    ]
