# Generated by Django 4.2.11 on 2024-04-02 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 4, 3), '03-04-2024'), (datetime.date(2024, 4, 4), '04-04-2024'), (datetime.date(2024, 4, 5), '05-04-2024'), (datetime.date(2024, 4, 6), '06-04-2024'), (datetime.date(2024, 4, 7), '07-04-2024'), (datetime.date(2024, 4, 8), '08-04-2024'), (datetime.date(2024, 4, 9), '09-04-2024')], max_length=20),
        ),
    ]
