# Generated by Django 4.2.11 on 2024-04-03 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 4, 4), '04-04-2024'), (datetime.date(2024, 4, 5), '05-04-2024'), (datetime.date(2024, 4, 6), '06-04-2024'), (datetime.date(2024, 4, 7), '07-04-2024'), (datetime.date(2024, 4, 8), '08-04-2024'), (datetime.date(2024, 4, 9), '09-04-2024'), (datetime.date(2024, 4, 10), '10-04-2024')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='issue',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
