# Generated by Django 4.2.11 on 2024-03-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0017_remove_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('solved', 'solved'), ('unsolved', 'unsolved')], default='unsolved', max_length=200)),
                ('patient_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
            options={
                'db_table': 'Doubt',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.doctor')),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubt.doubt')),
            ],
            options={
                'db_table': 'Solution',
            },
        ),
    ]
