# Generated by Django 4.2.11 on 2024-03-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
