# Generated by Django 4.2.11 on 2024-04-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0002_alter_doubt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='status',
            field=models.CharField(choices=[('solved', 'solved'), ('unsolved', 'unsolved')], default='unsolved', max_length=20),
        ),
    ]
